### ISSUE TITLE
Make SCS GX Credential Generator Gaia-X Compliant

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/gx-self-description-generator#55]
As a Cloud Provider, I want to offer my Openstack based IaaS cloud in a Gaia-X compatible Federation. In Gaia-X, each Service Offering MUST be describe by a Gaia-X Credential, which is authored by Cloud Provider. 

SCS Self-Description Generator facilitates the creation of Gaia-X credentials for Openstack based IaaS clouds, by generating parts of it, automatically. Howver, output of Self-Description Generator is not Gaia-X compliant.

This issue acts as epic for all issues, related to make SCS self-description generator Gaia-X compliant.

----
Process feedback Notes from reviewing the SD attributes:

- [x]  Virtualized CPU types: It might be of limited use to reference exact model names, rather characterize properties (generation, speed, insn set extensions, ...)
- [ ] NICs: Virtual NICs are almost unlimited, but there may be a limited amount of hardware-accelerated
  NICs (using SR-IOV and multiqueue features) available -- these may need to be added to SCS flavor
  naming.
- [ ] Other extension hardware like FPGAs need to be specified
- [ ] Tenant isolation needs a list of criteria. Virt OK? V(x)LANs OK? Shared storage cluster OK? ...
- [ ] Availability Zones: Provider needs to create transparency over what it means. Fire protection zones?
  Power supply zones? Internet connectivity zones? Minimal and maximal physical distance? Network
  latency distance?

**Comment by anjastrunk** [comment]
Related issues:

- [ ] https://github.com/SovereignCloudStack/gx-self-description-generator/issues/56
- [ ] https://github.com/SovereignCloudStack/gx-self-description-generator/issues/53
- [ ] https://github.com/SovereignCloudStack/gx-self-description-generator/issues/14
- [ ] https://github.com/SovereignCloudStack/gx-self-description-generator/issues/13

**Comment by anjastrunk** [comment]
Gaia-X Self-Description is renamed to Gaia-X Credentials. Maybe, we should rename SCS Gaia-X Self-Description Generator we well. See #61

**Comment by anjastrunk** [comment]
Gaia-X Self-Description is renamed in Gaia-X Credential. See [Architecture Doc](https://gitlab.com/gaia-x/technical-committee/architecture-document/-/merge_requests/480) . 

We should get rid of the old term "Self-Description" in our documentation. I update user story of this issue.

**Comment by anjastrunk** [comment]
Notes from reviewing the SD attributes:
* Virtualized CPU types: It might be of limited use to reference exact model names, rather characterize properties
  (generation, speed, insn set extensions, ...)
* NICs: Virtual NICs are almost unlimited, but there may be a limited amount of hardware-accelerated
  NICs (using SR-IOV and multiqueue features) available -- these may need to be added to SCS flavor
  naming.
* Other extension hardware like FPGAs need to be specified
* Tenant isolation needs a list of criteria. Virt OK? V(x)LANs OK? Shared storage cluster OK? ...
* Availability Zones: Provider needs to create transparency over what it means. Fire protection zones?
  Power supply zones? Internet connectivity zones? Minimal and maximal physical distance? Network
  latency distance?
